# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: 'win'
  pool:
    vmImage: windows-latest
  steps:
  - task: SpectralScan@0
    inputs:
        connection: 'spectral'

- job: 'linux'
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: SpectralScan@0
      inputs:
          connection: 'spectral'

- job: 'mac'
  pool:
    vmImage: macOS-latest
  steps:
    - task: SpectralScan@0
      inputs:
          connection: 'spectral'