# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: 'win'
  pool:
    vmImage: windows-latest
  variables:
    - name: DEBUG
      value: "true"
  steps:
  - task: SpectralScan@0.1.53
    inputs:
        connection: 'spectral'

- job: 'linux'
  pool:
    vmImage: ubuntu-latest
  variables:
      - name: DEBUG
        value: "true"
  steps:
    - task: SpectralScan@0.1.53
      inputs:
          connection: 'spectral'

- job: 'mac'
  pool:
    vmImage: macOS-latest
  variables:
        - name: DEBUG
          value: "true"
  steps:
    - task: SpectralScan@0.1.53
      inputs:
          connection: 'spectral'